services:
  app:
    build:
      context: .
      args:
        - POSTGRES_URL_NON_POOLING=${POSTGRES_URL_NON_POOLING}
    restart: always
    ports:
      - '4000:4000'
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PORT=4000
